#!/bin/bash

# This script should be run as the user, and runs the Utility on Login

# Install the launchctl services.
sudo -u $USER launchctl load -w /Library/LaunchAgents/com.github.goxlr-on-linux.goxlr-utility.plist
