#!/bin/bash

# This script configures the 'Out of the Box' GoXLR Utility to use the attached `goxlr-utility-ui` binary
# for configuration. This should be run as the User.
sudo -u $USER '/Applications/GoXLR Utility.app/Contents/MacOS/goxlr-utility-ui' --install
