#!/bin/bash

set -e
D="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# This script builds a binary dpkg for Debian based distros.
# Original script from ripgrep - https://github.com/BurntSushi/ripgrep (licensed MIT)
#
# Adapted for Cargo RPM
#
# Note that this requires 'cargo generate-rpm', which can be installed with
# 'cargo install cargo-generate-rpm'.
#
# This should be run from the root of the repo.

if ! command -V cargo-generate-rpm > /dev/null 2>&1; then
    echo "cargo-generate-rpm command missing" >&2
    exit 1
fi

# 'cargo deb' does not seem to provide a way to specify an asset that is
# created at build time. To work around this,
# we force a release build, copy out the shell completions
# produced from that build, put it into a predictable location and then build
# the deb, which knows where to look.
cargo build --release
strip -s target/release/goxlr-daemon
strip -s target/release/goxlr-client

DEPLOY_DIR=deployment/deb
OUT_DIR_CLIENT="$("$D"/cargo-out-dir target/release/ client-stamp)"
OUT_DIR_DAEMON="$("$D"/cargo-out-dir target/release/ daemon-stamp)"
mkdir -p "$DEPLOY_DIR"

# Copy man page and shell completions.
cp "$OUT_DIR_DAEMON"/{goxlr-daemon.bash,goxlr-daemon.fish,_goxlr-daemon} "$DEPLOY_DIR/"
cp "$OUT_DIR_CLIENT"/{goxlr-client.bash,goxlr-client.fish,_goxlr-client} "$DEPLOY_DIR/"

cargo generate-rpm -p daemon